# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gomod-patch-minor:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      gomod-major:
        patterns: ["*"]
        update-types: ["major"]
      x-libs:
        patterns: ["golang.org/x/*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha:
        patterns: ["*"]
