root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-port", "8090"]
  bin = "./tmp/main"
  cmd = "make generate && go build -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "og-site", "tests", "test-results", "bin"]
  exclude_file = ["Makefile", "README.md", ".gitignore", "assets/styles.css"]
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = ["cmd", "internal", "components", "css"]
  include_ext = ["go", "templ", "html", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[proxy]
  enabled = false
