FROM docker.io/alpine:latest

RUN apk add --no-cache ca-certificates tzdata && \
    adduser -D -H -h /app appuser

WORKDIR /app

COPY build/server /app/server
COPY assets/ /app/assets/
COPY examples/ /app/examples/
RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8090

ENTRYPOINT ["/app/server"]
