// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/guilycst/GoATTH-penguinui/components/combobox"
	"github.com/guilycst/GoATTH-penguinui/internal/pages/demo"
)

// ComboboxDemoPage renders the Combobox component demo
func ComboboxDemoPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = demo.Layout("Combobox", "combobox", comboboxDemoContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// comboboxDemoContent renders the actual content inside the layout
func comboboxDemoContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = demo.ComponentDemo(
			demo.ComponentDemoProps{
				Title:         "Combobox",
				Description:   "A combobox is an input widget with an associated popup that enables users to select a value from a collection of possible values.",
				OriginalURL:   "/original/combobox/simple-combobox.html",
				OriginalLabel: "Original PenguinUI",
				GoATTHLabel:   "GoATTH Component",
			},
			comboboxDemoPreview(),
			`// Simple Single-Select
@combobox.Combobox(combobox.Config{
    ID:          "industry",
    Label:       "Industry",
    Placeholder: "Select an industry",
    Options: []combobox.Option{
        {Value: "tech", Label: "Technology"},
        {Value: "health", Label: "Healthcare"},
        {Value: "finance", Label: "Finance"},
    },
})

// Multi-Select with Checkboxes
@combobox.Combobox(combobox.Config{
    ID:             "skills",
    Label:          "Skills",
    Mode:           combobox.ModeMultiple,
    EnableClearAll: true,
    Options: []combobox.Option{
        {Value: "go", Label: "Go"},
        {Value: "js", Label: "JavaScript"},
        {Value: "py", Label: "Python"},
    },
})

// With Search
@combobox.Combobox(combobox.Config{
    ID:           "country",
    Label:        "Country",
    EnableSearch: true,
    Options:      countries,
})

// With Images (Avatars)
@combobox.Combobox(combobox.Config{
    ID:      "user",
    Label:   "Share with",
    Options: users, // Options with Img field
})

// HTMX Lazy Loading
@combobox.Combobox(combobox.Config{
    ID:              "products",
    Label:           "Product",
    HXMTEndpoint:    "/api/products",
    EnableSearch:    true,
    HTMXSearchParam: "q",
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// comboboxDemoPreview renders the GoATTH combobox preview
func comboboxDemoPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full max-w-4xl mx-auto space-y-8\"><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">Single Select</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:          "industry",
			Label:       "Industry",
			Placeholder: "Select an industry",
			Name:        "industry",
			Options: []combobox.Option{
				{Value: "agriculture", Label: "Agriculture"},
				{Value: "construction", Label: "Construction"},
				{Value: "education", Label: "Education"},
				{Value: "entertainment", Label: "Entertainment"},
				{Value: "finance", Label: "Finance"},
				{Value: "healthcare", Label: "Healthcare"},
				{Value: "hospitality", Label: "Hospitality"},
				{Value: "it", Label: "IT"},
				{Value: "manufacturing", Label: "Manufacturing"},
				{Value: "marketing", Label: "Marketing"},
				{Value: "retail", Label: "Retail"},
				{Value: "transportation", Label: "Transportation"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">Single Select with Search</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:           "make",
			Label:        "Make",
			Placeholder:  "Select a make",
			Name:         "make",
			EnableSearch: true,
			Options: []combobox.Option{
				{Value: "acura", Label: "Acura"},
				{Value: "audi", Label: "Audi"},
				{Value: "bmw", Label: "BMW"},
				{Value: "chevrolet", Label: "Chevrolet"},
				{Value: "ferrari", Label: "Ferrari"},
				{Value: "ford", Label: "Ford"},
				{Value: "honda", Label: "Honda"},
				{Value: "hyundai", Label: "Hyundai"},
				{Value: "jaguar", Label: "Jaguar"},
				{Value: "kia", Label: "Kia"},
				{Value: "lexus", Label: "Lexus"},
				{Value: "mazda", Label: "Mazda"},
				{Value: "mercedes", Label: "Mercedes-Benz"},
				{Value: "nissan", Label: "Nissan"},
				{Value: "porsche", Label: "Porsche"},
				{Value: "tesla", Label: "Tesla"},
				{Value: "toyota", Label: "Toyota"},
				{Value: "volkswagen", Label: "Volkswagen"},
				{Value: "volvo", Label: "Volvo"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">Multi-Select with Checkboxes</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:             "skills",
			Label:          "Skills",
			Placeholder:    "Select skills",
			Name:           "skills",
			Mode:           combobox.ModeMultiple,
			EnableClearAll: true,
			Options: []combobox.Option{
				{Value: "cpp", Label: "C++"},
				{Value: "css", Label: "CSS"},
				{Value: "go", Label: "Go"},
				{Value: "html", Label: "HTML"},
				{Value: "java", Label: "Java"},
				{Value: "js", Label: "JavaScript"},
				{Value: "kotlin", Label: "Kotlin"},
				{Value: "php", Label: "PHP"},
				{Value: "python", Label: "Python"},
				{Value: "ruby", Label: "Ruby"},
				{Value: "rust", Label: "Rust"},
				{Value: "ts", Label: "TypeScript"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">Multi-Select with Search</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:             "languages",
			Label:          "Languages",
			Placeholder:    "Select languages",
			Name:           "languages",
			Mode:           combobox.ModeMultiple,
			EnableSearch:   true,
			EnableClearAll: true,
			Options: []combobox.Option{
				{Value: "en", Label: "English"},
				{Value: "es", Label: "Spanish"},
				{Value: "fr", Label: "French"},
				{Value: "de", Label: "German"},
				{Value: "it", Label: "Italian"},
				{Value: "pt", Label: "Portuguese"},
				{Value: "ru", Label: "Russian"},
				{Value: "zh", Label: "Chinese"},
				{Value: "ja", Label: "Japanese"},
				{Value: "ko", Label: "Korean"},
				{Value: "ar", Label: "Arabic"},
				{Value: "hi", Label: "Hindi"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">With Images</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:          "user",
			Label:       "Share with",
			Placeholder: "Select a user",
			Name:        "user",
			Options: []combobox.Option{
				{Value: "aiden", Label: "Aiden Walker", Img: "https://penguinui.s3.amazonaws.com/component-assets/avatar-1.webp"},
				{Value: "bob", Label: "Bob Johnson", Img: "https://penguinui.s3.amazonaws.com/component-assets/avatar-2.webp"},
				{Value: "emily", Label: "Emily Rodriguez", Img: "https://penguinui.s3.amazonaws.com/component-assets/avatar-3.webp"},
				{Value: "emma", Label: "Emma Thompson", Img: "https://penguinui.s3.amazonaws.com/component-assets/avatar-4.webp"},
				{Value: "alex", Label: "Alex Martinez", Img: "https://penguinui.s3.amazonaws.com/component-assets/avatar-5.webp"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">Pre-selected Values</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:             "preselected",
			Label:          "Frameworks",
			Placeholder:    "Select frameworks",
			Name:           "frameworks",
			Mode:           combobox.ModeMultiple,
			EnableClearAll: true,
			Selected:       []string{"react", "vue"},
			Options: []combobox.Option{
				{Value: "angular", Label: "Angular"},
				{Value: "react", Label: "React"},
				{Value: "svelte", Label: "Svelte"},
				{Value: "vue", Label: "Vue"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"max-w-xs\"><h4 class=\"text-sm font-medium mb-3 text-on-surface-strong dark:text-on-surface-dark-strong\">Disabled State</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = combobox.Combobox(combobox.Config{
			ID:       "disabled",
			Label:    "Disabled Combobox",
			Name:     "disabled",
			Disabled: true,
			Options: []combobox.Option{
				{Value: "a", Label: "Option A"},
				{Value: "b", Label: "Option B"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
